syntax = "proto3";

option java_package = "eu.altfive.playground.event";

// so that each message is defined in a different class
option java_multiple_files = true;

package agriflow.playground.event;

import "cc/variables/VariableValue.proto";

message ModelCreated {
  string id = 1;
  string name = 2;
}

message ParentSet {
  string id = 1;
  string parentId = 2;
}

message VariableAdded {
  string id = 1;
  string name = 2;
  cc.variables.VariableValue value = 3;
  repeated string parentIds = 4;
}

message VariableUpdated {
  string id = 1;
  string name = 2;
  cc.variables.VariableValue value = 3;
  repeated string parentIds = 4;
}