axon.axon-server.enabled=false
spring.elasticsearch.password=secret
axon.eventhandling.processors.elastic-model.mode=tracking
axon.eventhandling.processors.elastic-model.initial-segment-count=20
axon.eventhandling.processors.elastic-model.thread-count=20
axon.eventhandling.processors.elastic-model.batch-size=500
axon.eventhandling.processors.elastic-model.token-claim-interval=500
#axon.eventhandling.processors.elastic-nested.mode=tracking
#axon.eventhandling.processors.elastic-nested.initial-segment-count=1
#axon.eventhandling.processors.elastic-nested.thread-count=1
#axon.eventhandling.processors.elastic-nested.batch-size=500
#axon.eventhandling.processors.elastic-nested.sequencing-policy=customSequencingPolicy
axon.eventhandling.processors.elastic-nested-nobatch.mode=tracking
axon.eventhandling.processors.elastic-nested-nobatch.initial-segment-count=20
axon.eventhandling.processors.elastic-nested-nobatch.thread-count=20
spring.datasource.hikari.maximum-pool-size=50

spring.kafka.listener.concurrency=10

spring.kafka.bootstrap-servers=localhost:9092

###########
# CACHING #
###########
spring.cache.type=CAFFEINE
spring.cache.cache-names=axonCache
spring.cache.caffeine.spec=initialCapacity=1000,maximumSize=1000,expireAfterWrite=600s

axon.kafka.bootstrap-servers=localhost:9092
axon.kafka.client-id=axon-example
axon.kafka.default-topic=cc-local-event
axon.kafka.producer.event-processor-mode=subscribing
axon.kafka.fetcher.enabled=false

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer

#logging.level.org.springframework.kafka=DEBUG

spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;